### PR TITLE
Catch StorageNotAvailable exceptions

### LINKED ISSUE #992: Catch StorageNotAvailableException during propfinds
Turns out when having an unavailable storage this causes prop finds to fail due to checking for existance of Readme.md files.

Steps to reproduce are in https://github.com/nextcloud/server/issues/22461

```
{"reqId":"s0aRIe10JyBhiCYLdPZU","level":0,"time":"2020-08-27T15:59:57+00:00","remoteAddr":"192.168.21.10","user":"admin","app":"webdav","method":"PROPFIND","url":"/remote.php/webdav/","message":{"Exception":"OCP\\Files\\StorageNotAvailableException","Message":"","Code":1,"Trace":[{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Availability.php","line":243,"function":"checkAvailability","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->","args":[]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":226,"function":"file_exists","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->","args":["Readme.md"]},{"file":"/var/www/html/lib/private/Files/View.php","line":1334,"function":"file_exists","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["Readme.md"]},{"file":"/var/www/html/lib/private/Files/View.php","line":1383,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"Readme.md","/admin/files/NC2/Readme.md"]},{"file":"/var/www/html/lib/private/Files/Node/Root.php","line":201,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["/admin/files/NC2/Readme.md"]},{"file":"/var/www/html/lib/private/Files/Node/Folder.php","line":140,"function":"get","class":"OC\\Files\\Node\\Root","type":"->","args":["/admin/files/NC2/Readme.md"]},{"file":"/var/www/html/lib/private/Files/Node/Folder.php","line":149,"function":"get","class":"OC\\Files\\Node\\Folder","type":"->","args":["Readme.md"]},{"file":"/var/www/html/apps-extra/text/lib/Service/WorkspaceService.php","line":32,"function":"nodeExists","class":"OC\\Files\\Node\\Folder","type":"->","args":["Readme.md"]},{"file":"/var/www/html/apps-extra/text/lib/DAV/WorkspacePlugin.php","line":101,"function":"getFile","class":"OCA\\Text\\Service\\WorkspaceService","type":"->","args":[{"__class__":"OC\\Files\\Node\\Folder"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":96,"function":"OCA\\Text\\DAV\\{closure}","class":"OCA\\Text\\DAV\\WorkspacePlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps-extra/text/lib/DAV/WorkspacePlugin.php","line":107,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->","args":["{http://nextcloud.org/ns}rich-workspace",{"__class__":"Closure"}]},{"file":"/var/www/html/apps-extra/mail/vendor/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"OCA\\Text\\DAV\\WorkspacePlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1063,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["propFind",[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":989,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1678,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["",["{http://owncloud.org/ns}owner-id","{DAV:}creationdate","{DAV:}getetag","{http://owncloud.org/ns}permissions","{DAV:}getlastmodified","{http://owncloud.org/ns}id","{DAV:}getcontentlength","{http://owncloud.org/ns}favorite","{DAV:}resourcetype","{http://nextcloud.org/ns}sharees","{http://nextcloud.org/ns}mount-type","{http://nextcloud.org/ns}rich-workspace","{DAV:}displayname","{http://nextcloud.org/ns}note","{DAV:}getcontenttype","{http://nextcloud.org/ns}has-preview","{http://owncloud.org/ns}size","{http://nextcloud.org/ns}is-encrypted","{http://owncloud.org/ns}owner-display-name","{http://owncloud.org/ns}comments-unread"],1]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"elementMap":[],"contextUri":"/remote.php/webdav/","namespaceMap":{"DAV:":"d","http://sabredav.org/ns":"s","http://owncloud.org/ns":"oc","http://nextcloud.org/ns":"nc"},"classMap":[],"__class__":"Sabre\\Xml\\Writer"},{"__class__":"Generator"},false]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":363,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"file":"/var/www/html/apps-extra/mail/vendor/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PROPFIND",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v1/webdav.php","line":84,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":167,"args":["/var/www/html/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Files/Storage/Wrapper/Availability.php","Line":94,"Hint":"Storage is temporarily not available","CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/20200827","version":"20.0.0.4"}
```

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #992 

This could have caused the android app to not show a folder if any subdirectory contained an unavailable storage.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
sure

File: lib/DAV/WorkspacePlugin.php [hunk 1]
```diff
@@ -98,9 +99,12 @@ public function propFind(PropFind $propFind, INode $node) {
...
 				/** @var File $file */
-				$file = $this->workspaceService->getFile($nodes[0]);
-				if ($file instanceof File) {
-					return $file->getContent();
+				try {
+					$file = $this->workspaceService->getFile($nodes[0]);
+					if ($file instanceof File) {
+						return $file->getContent();
+					}
+				} catch (StorageNotAvailableException $e) {
```
Comment (ChristophWurst) [inline lib/DAV/WorkspacePlugin.php:107]: mind adding a code comment about why the exception is ignored silently?

Comment (juliushaertl) [reply lib/DAV/WorkspacePlugin.php:107]: sure

**Review by ChristophWurst — APPROVED** [review]
