### PR TITLE
fix: Add migration to drop conflicting index ts_session

### LINKED ISSUE #4958: Cleanup potential duplicated index
In NC 27.0.1 RC2 we had an index which was colliding with one in the Talk app. This was fixed for 27.0.1 proper (#4553), nevertheless some people already ran into issues with the upgrade to 28.0.0 Beta 1, because a potentially existing index was not removed (cf. https://help.nextcloud.com/t/first-beta-of-nextcloud-28/173501/6 and https://help.nextcloud.com/t/first-beta-of-nextcloud-28/173501/12).

### PR DESCRIPTION
**Pull request by juliushaertl**
Fix #4958 for instances that had the broken beta release installed.

### CODE REVIEW

File: lib/Migration/Version03009Date20231114150437.php [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+ */
+
+namespace OCA\Text\Migration;
+
+use Closure;
+use OCP\DB\ISchemaWrapper;
+use OCP\Migration\IOutput;
+use OCP\Migration\SimpleMigrationStep;
+
+class Version03009Date20231114150437 extends SimpleMigrationStep {
```
Comment (juliushaertl) [inline lib/Migration/Version03009Date20231114150437.php:34]: Apparently the version schema is different from what occ migration:generate suggest. It should be 3009 starting with that now would cause the migrations on new setups to run in the wrong order.

@nickvergessen Do you see any issue with continuing with the 0 padded major version? Is there any possible migration path to e.g. merge existing migration steps into one matching the new schema?

Comment (mejo-) [reply lib/Migration/Version03009Date20231114150437.php:34]: Shouldn't this version string actually start with `030901` given the version 3.9.1?

**Review by mejo- — APPROVED** [review]
Looks good apart from the question about the version string.

File: lib/Migration/Version03009Date20231114150437.php (hunk 1 above)
Comment (juliushaertl) [reply lib/Migration/Version03009Date20231114150437.php:34]: No just major/minor:

> We recommend to use the major and minor digits of your apps version for that. This allows you to introduce a new migration in your branch for a Nextcloud version if there is already a migration path for a newer one in another branch. Since you can’t change this retroactive, we recommend to leave enough space in between and therefore map the numbers to 3 digits: `1.0.x => 1000, 2.34.x => 2034, etc.

https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/migrations.html

Comment (juliushaertl) [reply lib/Migration/Version03009Date20231114150437.php:34]: Ah it only gets executed first because I also overseen the extra minor step that I added. However looking at https://github.com/nextcloud/server/blob/6f39d82031202a2a8d1fb81ea448a2ffdc52cc29/lib/private/DB/MigrationService.php#L223-L231 i think it should be fine to just continue with our current pattern

Comment (nickvergessen) [reply lib/Migration/Version03009Date20231114150437.php:34]: Yeah should work

File: composer/composer/autoload_classmap.php [hunk 2]
```diff
@@ -49,6 +49,7 @@
     'OCA\\Text\\Migration\\ResetSessionsBeforeYjs' => $baseDir . '/../lib/Migration/ResetSessionsBeforeYjs.php',
     'OCA\\Text\\Migration\\Version010000Date20190617184535' => $baseDir . '/../lib/Migration/Version010000Date20190617184535.php',
     'OCA\\Text\\Migration\\Version030001Date20200402075029' => $baseDir . '/../lib/Migration/Version030001Date20200402075029.php',
+    'OCA\\Text\\Migration\\Version03009Date20231114150437' => $baseDir . '/../lib/Migration/Version03009Date20231114150437.php',
```
[the remark this answers is not in the document]
Comment (juliushaertl) [reply composer/composer/autoload_classmap.php]: You were actually right that existing migrations followed AABBCC (major/minor/patch) format. Adjusted that.

**Review by blizzz — APPROVED** [review]
