### PR TITLE
fix(paste): collapse whitespace before pasting

### LINKED ISSUE #4602: Pasting paragraphs sometimes adds unexpected linebreaks
**Describe the bug**
When pasting paragraphs to a document, sometimes unexpected linebreaks are added in between the paragraph. As soon as you do one change in the paragraph, all unexpected linebreaks get deleted at once.

As an example, paste the first 3-4 paragraphs of the [wikipedia article about Fairy Tales](https://en.wikipedia.org/wiki/Fairy_tale) into a document.

**To Reproduce**
1. Open a document, paste the example paragraph from above.
2. See unexpected linebreaks
3. Add one character anywhere in the paragraph
4. The the unexpected linebreaks disappearing.

### PR DESCRIPTION
**Pull request by max-nextcloud**
### 📝 Summary

By default html does not display whitespace but text does. Remove newlines when pasting to ensure consistency with the previous display.

Keep the newlines when they are also displayed in the source.

* Resolves: #4602
* Resolves: #4768
* Superseedes: #4624 

#### 🏚️ Before

grafik 

#### 🏡 After

grafik

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation is not required

### CODE REVIEW

File: src/extensions/transformPastedHTML.js [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+	// Values of `white-space` css that will collapse newline whitespace
+	// See https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#values
+	const COLLAPSING_WHITE_SPACE_VALUES = ['normal', 'nowrap']
+	let ancestor = textNode.parentElement
+	while (ancestor) {
+		const style = getComputedStyle(ancestor)
+		const whiteSpace = style?.getPropertyValue('white-space')
+		if (whiteSpace) {
+			return COLLAPSING_WHITE_SPACE_VALUES.includes(whiteSpace)
+		}
```
Comment (max-nextcloud) [inline src/extensions/transformPastedHTML.js:87]: While this is more precise as it also detects `<div style="white-space: pre-wrap">` and `<pre><em style="white-space: normal">` it's only supported in Firefox. So not sure if it's worthwhile the inconsistency and extra logic.

**Comment by mejo-** [comment]
Probably also will fix https://github.com/nextcloud/text/issues/4768.

File: src/extensions/transformPastedHTML.js [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+function collapseWhiteSpace(textNode) {
+	// Values of `white-space` css that will collapse newline whitespace
+	// See https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#values
+	const COLLAPSING_WHITE_SPACE_VALUES = ['normal', 'nowrap']
+	let ancestor = textNode.parentElement
+	while (ancestor) {
+		const style = getComputedStyle(ancestor)
+		const whiteSpace = style?.getPropertyValue('white-space')
+		if (whiteSpace) {
+			return COLLAPSING_WHITE_SPACE_VALUES.includes(whiteSpace)
```
Comment (mejo-) [inline src/extensions/transformPastedHTML.js:86]: Maybe a short explanationary comment above this line: `// Returns false if white-space has a value not listed in COLLAPSING_WHITE_SPACE_VALUES`.

File: src/extensions/transformPastedHTML.js (hunk 1 above)
Comment (mejo-) [reply src/extensions/transformPastedHTML.js:87]: I'm in favour of keeping the extra logic nevertheless. I'd move the comment from below to the top of `while(ancestor)` though and add something like:
> // Therefore the following logic only works on Firefox

Then an empty line before the `ancestor.tagName === 'PRE'` part and another comment above:
> // Check for `tagName` as fallback

**Review by mejo- — APPROVED** [review]
Max gave me a walkthrough through the code. Very clean and thorough solution, thanks a lot! Only nitpicking comments.

**Comment by mejo-** [comment]
Cypress failures are unrelated.
