### PR TITLE
fix: Delete inactive sessions in one query

### LINKED ISSUE #4218: [Bug]: cron.php generates "More than 1000 expressions in a list are not allowed on Oracle" error
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Running `sudo -u www-data /usr/bin/php -f /opt/nextcloud/cron.php` will log an error containing

```json
{
  "Exception": "DoctrineDBALQueryQueryException",
  "Message": "More than 1000 expressions in a list are not allowed on Oracle.",
  "Code": 0,
  "Trace": [
    {
      "file": "/opt/nextcloud/apps/text/lib/Db/SessionMapper.php",
      "line": 122,
      "function": "execute",
      "class": "OCDBQueryBuilderQueryBuilder",
      "type": "->"
    },
    {
      "file": "/opt/nextcloud/apps/text/lib/Service/SessionService.php",
      "line": 151,
      "function": "deleteInactiveWithoutSteps",
      "class": "OCATextDbSessionMapper",
      "type": "->"
    },
    {
      "file": "/opt/nextcloud/apps/text/lib/Cron/Cleanup.php",
      "line": 76,
      "function": "removeInactiveSessionsWithoutSteps",
      "class": "OCATextServiceSessionService",
      "type": "->"
    },
    {
      "file": "/opt/nextcloud/lib/public/BackgroundJob/Job.php",
      "line": 78,
      "function": "run",
      "class": "OCATextCronCleanup",
      "type": "->"
    },
    {
      "file": "/opt/nextcloud/lib/public/BackgroundJob/TimedJob.php",
      "line": 103,
      "function": "start",
      "class": "OCPBackgroundJobJob",
      "type": "->"
    },
    {
      "file": "/opt/nextcloud/lib/public/BackgroundJob/TimedJob.php",
      "line": 93,
      "function": "start",
      "class": "OCPBackgroundJobTimedJob",
      "type": "->"
    },
    {
      "file": "/opt/nextcloud/cron.php",
      "line": 152,
      "function": "execute",
      "class": "OCPBackgroundJobTimedJob",
      "type": "->"
    }
  ],
  "File": "/opt/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
  "Line": 263,
  "message": "More than 1000 expressions in a list are not allowed on Oracle.",
  "query": "DELETE FROM `*PREFIX*text_sessions` WHERE (`last_contact` < :dcValue1) AND (`id` NOT IN (:dcValue2))",
  "exception": {},
  "CustomMessage": "More than 1000 expressions in a list are not allowed on Oracle."
}
```

### Steps to reproduce

1. `sudo -u www-data /usr/bin/php -f /opt/nextcloud/cron.php`
2.
3.

### Expected behavior

Error should not occur?

### Installation method

None

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

_No response_

### List of activated Apps

```shell
.
```

### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #4218 

Delete inactive sessions without steps in one query as the oracle limit is only about 1000 expressions. Using one query also has the benefit to avoid deadlock scenarios as the query would lock the rows directly.

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] [Tests](https://github.com/nextcloud/text#-testing-the-app) (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/text/blob/main/README.md) or [documentation](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/text_configuration.rst#L2)) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Sqlite somehow fails, but only on CI 🙈 

1) OCA\Text\Db\SessionMapperTest::testDeleteInactiveWithoutSteps1010
Failed asserting that actual size 1009 matches expected size 0.

/home/runner/actions-runner/_work/text/text/apps/text/tests/unit/Db/SessionMapperTest.php:97

File: lib/Migration/Version030901Date20230615085512.php [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+	 */
+	public function changeSchema(IOutput $output, Closure $schemaClosure, array $options) {
+		/** @var ISchemaWrapper $schema */
+		$schema = $schemaClosure();
+
+		$table = $schema->getTable('text_steps');
+		if (!$table->hasIndex('ts_session')) {
+			$table->addIndex(['session_id'], 'ts_session');
+			return $schema;
+		}
```
Comment (blizzz) [inline lib/Migration/Version030901Date20230615085512.php:28]: Doing it live on upgrade, do think it'll take long? For example, we have almost 300k entries in that table.

Comment (juliushaertl) [reply lib/Migration/Version030901Date20230615085512.php:28]: Yes, tough this is how apps currently do it as far as I can tell. There is a internal/deprecated ADD_MISSING_INDEXES_EVENT but I couldn't find any usage of it. Let me see if that works, maybe we can just introduce an OCP event for that then as well.

Comment (blizzz) [reply lib/Migration/Version030901Date20230615085512.php:28]: For it can run while the instance is life, one of the one-time repair/migration job types would do it, even without manual intervention.

Comment (blizzz) [reply lib/Migration/Version030901Date20230615085512.php:28]: … but if course that would not be very consistent with usual NC ops.

Comment (juliushaertl) [reply lib/Migration/Version030901Date20230615085512.php:28]: Right, I think I'll still go with the event then as this allows admins to run it during off peak hours. The query itself is already faster than before even without the index.

Comment (blizzz) [reply lib/Migration/Version030901Date20230615085512.php:28]: Background jobs can also run during off-peak hours =) but yes, i concur it's the best apporach.

**Comment by juliushaertl** [comment]
Let me split this to have only the query change as a backportable fix, as mentioned above the index could be considered a separate enhancement

**Comment by juliushaertl** [comment]
@blizzz @mejo- 🏓 for a review, would be nice to get this in for the next maintenance release to reduce log spam on our instance ;)

**Comment by blizzz** [comment]
> @blizzz @mejo- ping_pong for a review, would be nice to get this in for the next maintenance release to reduce log spam on our instance ;)

please trigger the necessary backports
