### PR TITLE
Fix rich workspaces on case insensitive filesystems

### LINKED ISSUE #807: Readme, readme and README on external HDD
### Steps to reproduce
1. run NC in docker
2. disk mount `UUID=623C-1C23  /media/ex_320G    vfat    uid=33,gid=33  0    0`
3. add volume in docker compose `- /media/ex_320G:/hostfs/media/ex_320G`
4. add disk with "External Storage Support" app
5. go to disk and create `Readme.md`

### Expected behaviour
`Readme.md` file is created

### Actual behaviour
After some time (few seconds) 3 files are visible in NC
* `Readme.md`
* `README.md`
* `readme.md`

### Server configuration

**Operating system:**
Ubuntu 18.04

**Web server:**
latest docker

**Database:**
latest docker

**PHP version:**
latest docker

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
official docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - breezedark: 18.0.8
  - bruteforcesettings: 1.5.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - drawio: 0.9.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - geoblocker: 0.2.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_admin: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_gateway: 0.15.1
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
             "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.1.3",
        "overwrite.cli.url":  "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwritehost":  "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "maintenance": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

Also described here: https://help.nextcloud.com/t/readme-readme-and-readme-on-external-hdd/72730

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #807 

This fixes multiple files showing up on case-insensitive filenames as otherwise
the IFolder::get call creates multiple entries in the filecache for the same file. In addition to the fix now the behaviour is actually the correct one where the first matching filename of supported names is picked up for creating the file and obtaining in case there are multiple names matching.

### CODE REVIEW

File: src/views/RichWorkspace.vue [hunk 1]
```diff
@@ -149,7 +149,7 @@ export default {
 				return
 			}
 			this.creating = true
-			window.FileList.createFile('Readme.md', { scrollTo: false, animate: false }).then((status, data) => {
+			window.FileList.createFile(t('text', 'Readme') + '.md', { scrollTo: false, animate: false }).then((status, data) => {
```
Comment (kesselb) [inline src/views/RichWorkspace.vue:152]: Mind to explain that change :thinking: You want to support 'Liesmich.md` as well :rofl:

Comment (juliushaertl) [reply src/views/RichWorkspace.vue:152]: This is mainly fixing the behavior I assumed I had already implemented :see_no_evil: 

See https://github.com/nextcloud/text/issues/727#issuecomment-608028652 for the discussion on the translated file name :wink: 

I also find the german "Anleitung.md" a bit odd, but also agree with @jancborchardt that Readme.md is a quite technical description that might confuse users.

Comment (kesselb) [reply src/views/RichWorkspace.vue:152]: Oh :) I think translating the file name is a mistake. You add a lot of complexity and weirdness but fine by me.

Comment (kesselb) [reply src/views/RichWorkspace.vue:152]: A note: I think using a translated `Readme` to create a file is bad.

The current assumption is that everyone uses the same language:

1. We have Alice (lang: german) and Bob (lang: english)
2. Alice creates a folder and uses rich workspace. A file `Anleitung.md` is created.
3. Alice shares the Folder to Bob.
4. Bob does not see rich workspace because `Anleitung.md` is not a valid file name for him. 
5. Bob also uses rich workspace. A file `Readme.md` is created. 
6. They both edit rich workspace but do not see their changes ;)

Comment (juliushaertl) [reply src/views/RichWorkspace.vue]: That is a very good point actually. Then we probably should keep Readme.md as the default and just allow the translated name to be picked up if such a file exists. What do you think @jancborchardt 

I removed this commit from the PR now since it is actually unrelated to the fix for #807 it just was my first trace to the bug. ;)

Comment (jancborchardt) [reply src/views/RichWorkspace.vue]: > What do you think @jancborchardt

I always think that the task of software is to reduce complexity towards people using the software – and yes that means more complexity in the code, which is fine. :) It will be very strange to any non-English speaker, especially non-native, if a file called "Readme.md" shows up in their file list.


------

> Every application has an inherent amount of irreducible complexity. The only question is: Who will have to deal with it—the user, the application developer, or the platform developer?

See https://en.wikipedia.org/wiki/Law_of_conservation_of_complexity

Comment (jancborchardt) [reply src/views/RichWorkspace.vue]: And just to clarify: I do realize this would probably be a ton of work, so feel free to put it very far down on the todo list or not on it at all. ;)
(Also, there might be confusion the other way around when someone on the team says "Check the readme" and it’s called differently for everyone.)

**Comment by JMoVS** [comment]
if this was supposed to fix multiple Readme.md being created on case insensitive file systems - it did not fix it as shown in #1546
