### PR TITLE
Disable attachment upload on federated shares

### LINKED ISSUE #7092: Attaching a file to a federated share should be blocked.
**Describe the bug**
Currently it's not possible to attach a file to a federated share of a markdown file.

We should disable the corresponding buttons in the ui and add a tooltip explaining why no files can be attached.

On the server side attempting to attach a file throws 'File has no owner' in the getAttachmentDirectoryForFile function.

**To Reproduce**
1. Share a file with another nextcloud instance via federation.
2. Open that file on the other instance.
3. Try to add an attachment to it.

**Expected behavior**
The button should be disabled and a tooltip should explain why.

**Screenshots**
Will be added later.

**Server details:**
- Nextcloud version: 28

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```json
{
  "url": "/apps/text/attachment/upload?documentId=",
  "exception": {
    "Exception": "OCP\\Files\\NotFoundException",
    "Message": "File has no owner",
    "Code": 0,
    "Trace": [
      {
        "file": "/opt/nextcloud/apps/text/lib/Service/AttachmentService.php",
        "line": 287,
        "function": "getAttachmentDirectoryForFile",
        "class": "OCA\\Text\\Service\\AttachmentService",
        "type": "->"
      },
      {
        "file": "/opt/nextcloud/apps/text/lib/Controller/AttachmentController.php",
        "line": 144,
        "function": "uploadAttachment",
        "class": "OCA\\Text\\Service\\AttachmentService",
        "type": "->"
      },
      {
        "file": "/opt/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 230,
        "function": "uploadAttachment",
        "class": "OCA\\Text\\Controller\\AttachmentController",
        "type": "->"
      },
      {
        "file": "/opt/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 137,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/opt/nextcloud/lib/private/AppFramework/App.php",
        "line": 184,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/opt/nextcloud/lib/private/Route/Router.php",
        "line": 315,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/opt/nextcloud/lib/base.php",
        "line": 1069,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/opt/nextcloud/index.php",
        "line": 39,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/opt/nextcloud/apps/text/lib/Service/AttachmentService.php",
    "Line": 436,
    "message": "Upload error",
    "exception": {},
    "CustomMessage": "Upload error"
  }
}

```

</details>

### PR DESCRIPTION
**Pull request by max-nextcloud**
Fixes #7092 

Files without an owner such as federated shares
cannot receive attachments
as the attachment would need to be stored in the owners user folder.

TODO:

* [x] unit test for backend
* [x] add `syncService.hasOwner`
* [x] frontend: disable attachments in SuggestionBar
* [x] frontend: disable attachments in MenuBar
* [x] decission: What to do about picking files from cloud

### CODE REVIEW

File: tests/unit/Service/ApiServiceTest.php [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+		);
+	}
+
+	public function testCreateNewSession() {
+		$file = $this->createMock(\OCP\Files\File::class);
+		$storage = $this->createMock(\OCP\Files\Storage\IStorage::class);
+		$document = $this->createMock(\OCA\Text\Db\Document::class);
+		$file->method('getStorage')->willReturn($storage);
+		$file->method('getId')->willReturn(1234);
+		$document->method('getId')->willReturn(1234);
```
Comment (max-nextcloud) [inline tests/unit/Service/ApiServiceTest.php:56]: This currently fails with:
```
1) OCA\Text\Tests\ApiServiceTest::testCreateNewSession
PHPUnit\Framework\MockObject\MethodCannotBeConfiguredException: Trying to configure method "getId" which cannot be configured because it does not exist, has not been specified, is final, or is static

/var/www/html/apps/text/tests/unit/Service/ApiServiceTest.php:56

```

**Review by mejo- — APPROVED** [review]
Didn't test, but the code changes look sensible to me. Extra kudos for the tests :test_tube:
